services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keeper
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5