name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: install tools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.1
      - name: golangci-lint
        run: |
          golangci-lint run --timeout 5m --config ./.golangci.yml -v